name: Build Homepage
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    - main
jobs:
  build-docker:
    name: Build and push Docker image 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/untanky/homepage:latest
